### ISSUE TITLE
Hinder Events from duplicating events when storing them to the database

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#307] opened 2023-03-14 11:26 UTC
### Description

Erorrhandling of inbound events can result in an event being persisted multiple times in the database. 

### Tasks

- [ ] Investigate logs and see if we can find the point of failiure

**Comment by SandGrainOne** [comment] 2023-03-21 09:04
Refinement 21.03.2023:
The issue isn't serius enough for us to switch our focus to this now. This will instead be taken in when we look at replacing Azure Storage Queue with a Kafka event stream.

**Comment by olebhansen** [comment] 2024-08-12 09:07
Pending implementation of #573 and subsequent observations to determine if additional work is needed.

**Comment by olebhansen** [comment] 2024-09-17 12:00
Closing - resolving this in https://github.com/Altinn/altinn-events/issues/588

**Closed by olebhansen** 2024-09-17 12:00 UTC
Labels: kind/user-story, status/draft, status/blocked
